/**
 * Provision Umami for local development.
 *
 * - Waits for Umami to be healthy
 * - Logs in with default credentials
 * - Creates the "Cleancentive Dev" website if it doesn't exist
 * - Writes VITE_UMAMI_WEBSITE_ID to frontend/.env.local
 *
 * Idempotent — safe to run on every `bun dev`.
 */

import fs from 'node:fs';
import path from 'node:path';

const UMAMI_URL = 'http://localhost:3001';
const UMAMI_USERNAME = 'admin';
const UMAMI_PASSWORD = 'umami';
const WEBSITE_NAME = 'Cleancentive Dev';
const WEBSITE_DOMAIN = 'localhost';
const ENV_LOCAL_PATH = path.resolve(import.meta.dir, '..', 'frontend', '.env.local');

async function waitForUmami(maxAttempts = 30) {
  for (let i = 0; i < maxAttempts; i++) {
    try {
      const res = await fetch(`${UMAMI_URL}/api/heartbeat`);
      if (res.ok) return;
    } catch {}
    await new Promise((r) => setTimeout(r, 2000));
  }
  throw new Error('Umami did not become healthy within 60s');
}

async function login(): Promise<string> {
  const res = await fetch(`${UMAMI_URL}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ username: UMAMI_USERNAME, password: UMAMI_PASSWORD }),
  });
  if (!res.ok) throw new Error(`Umami login failed: ${res.status}`);
  const data = (await res.json()) as { token: string };
  return data.token;
}

async function getOrCreateWebsite(token: string): Promise<string> {
  const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };

  // Check for existing website
  const listRes = await fetch(`${UMAMI_URL}/api/websites`, { headers });
  const list = (await listRes.json()) as { data: Array<{ id: string; name: string }> };
  const existing = list.data.find((w) => w.name === WEBSITE_NAME);
  if (existing) return existing.id;

  // Create new website
  const createRes = await fetch(`${UMAMI_URL}/api/websites`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ name: WEBSITE_NAME, domain: WEBSITE_DOMAIN }),
  });
  if (!createRes.ok) throw new Error(`Failed to create Umami website: ${createRes.status}`);
  const created = (await createRes.json()) as { id: string };
  return created.id;
}

function writeEnvLocal(websiteId: string) {
  const scriptUrl = `${UMAMI_URL}/script.js`;
  const umamiLines = [
    `VITE_UMAMI_SCRIPT_URL=${scriptUrl}`,
    `VITE_UMAMI_WEBSITE_ID=${websiteId}`,
  ];

  let content = '';
  if (fs.existsSync(ENV_LOCAL_PATH)) {
    content = fs.readFileSync(ENV_LOCAL_PATH, 'utf-8');
    // Replace existing Umami lines or append
    for (const line of umamiLines) {
      const key = line.split('=')[0];
      const regex = new RegExp(`^${key}=.*$`, 'm');
      if (regex.test(content)) {
        content = content.replace(regex, line);
      } else {
        content = content.trimEnd() + '\n' + line + '\n';
      }
    }
  } else {
    content = '# Auto-generated by infrastructure/setup-umami.ts\n' + umamiLines.join('\n') + '\n';
  }

  fs.writeFileSync(ENV_LOCAL_PATH, content);
}

try {
  console.log('Umami: waiting for service...');
  await waitForUmami();
  const token = await login();
  const websiteId = await getOrCreateWebsite(token);
  writeEnvLocal(websiteId);
  console.log(`Umami: ready (website ${websiteId})`);
} catch (e) {
  console.warn(`Umami setup skipped: ${e instanceof Error ? e.message : e}`);
}
